### ISSUE TITLE
Example instance doesn't work

### ISSUE THREAD

**Issue by ghost** [rothgar/static-mastodon#3]
mastodon.jgarr.net don't work with infinity redirects error. I'm only find profile in mastodon.social cache. And I'm trying doing the same file structure, but my profile is not displayed (@test@bot.doesnm.cc)

**Comment by rothgar** [comment]
Sorry, I broke this when moving registrars. I'll figure it out

**Comment by ghost** [comment]
When will you fix it?

**Comment by rothgar** [comment]
It's fixed now

**Comment by ghost** [comment]
> From any mastodon instance

But why profile shows only on mastodon.social ?

**Comment by rothgar** [comment]
I'm not sure why it doesn't work from other instances. Maybe their installations are old or don't discover users according to AcitivityPub.

You can test the URLs by following it manually with curl

```
curl -L https://mastodon.jgarr.net/.well-known/webfinger
{
    "subject": "acct:justin@mastodon.jgarr.net",
    "links": [{
        "rel": "self",
        "type": "application/activity+json",
        "href": "https://mastodon.jgarr.net/justin"
    }]
}
```

**Comment by ghost** [comment]
I'm makes similar but my profile not shown on mastodon.social
```
curl -L https://bot.doesnm.cc/.well-known/webfinger
{
    "subject": "acct:test@bot.doesnm.cc",
    "links": [{
        "rel": "self",
        "type": "application/activity+json",
        "href": "https://bot.doesnm.cc/test"
    }]
}
```

**Comment by p37307** [comment]
Both accounts show from my self-hosted instance Explore search, which isn't mastodon.social.
![image](https://github.com/rothgar/static-mastodon/assets/22573401/13c75815-687c-4aca-9649-281dbe046371)

![image](https://github.com/rothgar/static-mastodon/assets/22573401/3c6cb531-1786-4b75-b838-915d9ee1722d)

**Comment by ghost** [comment]
I'm trying mastodon.social, mastodon.ml, masturbated.one
Upd: also tried mozilla.social

**Comment by rothgar** [comment]
This isn't a full featured solution and I'm not surprised if it doesn't work anymore. It may just be that my user was cached in mastodon social when it worked and it doesn't anymore

**Comment by ghost** [comment]
Then why do both profiles work for a person from above?
